export const settingsdata = {
  showhud: {
    name: "showhud",
    label: "Toggle Hud",
    description: "Randoma",
    show: true,
    value: true,
    type: "button",
    category: "general",
  },
  cinematicmode: {
    name: "cinematicmode",
    label: "Cinemtic Mode",
    description: "Random",
    show: true,
    value: false,
    type: "button",
    category: "general",
  },
  fliphud: {
    name: "fliphud",
    label: "Flip Hud",
    description: "Random",
    show: true,
    value: false,
    type: "button",
    category: "general",
  },
  showminimap: {
    name: "showminimap",
    label: "Toggle Minimap",
    description: "Random",
    show: true,
    value: true,
    type: "button",
    category: "minimap",
  },
  skullonfoot: {
    name: "skullonfoot",
    label: "Skull on foot",
    description: "Random",
    show: true,
    value: false,
    type: "button",
    category: "minimap",
  },
  minimapextrastatus: {
    name: 'minimapextrastatus',
    label: 'Toggle Minimap Status',
    description: "This option is for you to decide if you want to enable or disable the minimap extra status for example hunger thirst stress etc",
    show: true,
    value: true,
    type: 'button',
    category: 'minimap'
},
  minimapsize: {
    name: "minimapsize",
    label: "Minimap Size",
    description: "Random",
    show: true,
    value: 10,
    type: "slider",
    category: "minimap",
  },
  showspeedometer: {
    name: "showspeedometer",
    label: "Toggle Speedometer",
    description: "This options is for you to decided if you want to enable or disable the speedometer of the hud",
    show: true,
    value: true,
    type: "button",
    category: "speedometer",
  },
  speedometersize: {
    name: "speedometersize",
    label: "Speedometer Scale",
    description: "Random",
    show: true,
    value: 10,
    type: "slider",
    category: "speedometer",
  },
  mphkmh: {
    name: "mphkmh",
    label: "Vehicle Speed Unit",
    description: "Random",
    show: true,
    value: true,
    option1: "MPH",
    option2: "KMH",
    type: "select",
    category: "speedometer",
  },
  compassize: {
    name: "compassize",
    label: "Compass Scale",
    description: "Random",
    show: true,
    value: 10,
    type: "slider",
    category: "speedometer",
  },
  showcompass: {
    name: "showcompass",
    label: "Toggle Compass",
    description: "Random",
    show: true,
    value: true,
    type: "button",
    category: "speedometer",
  },
  showstreet: {
    name: "showstreet",
    label: "Toggle Street Names",
    description: "Random",
    show: true,
    value: true,
    type: "button",
    category: "speedometer",
  },
  seatbeltalarm: {
    name: "seatbeltalarm",
    label: "Toggle Seatbelt Alarm",
    description: "Random",
    show: true,
    value: true,
    type: "button",
    category: "speedometer",
  },
  showinfo: {
    name: "showinfo",
    label: "Toggle Info",
    description: "Random",
    show: true,
    value: true,
    type: "button",
    category: "info",
  },
  dynamicinfo: {
    name: "dynamicinfo",
    label: "Dynamic Info",
    description: "Random",
    show: true,
    value: true,
    type: "button",
    category: "info",
  },
};
